"""empty message

Revision ID: 2a9718cc6d78
Revises: 
Create Date: 2022-01-27 04:20:33.702271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a9718cc6d78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('moderator', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    op.drop_column('user', 'moderator')
    # ### end Alembic commands ###
